[package]
name = "chasma"
version = "0.1.0"
edition = "2021"
authors = ["Matthew Dewyer"]
description = "An RTSâ€style terrain demo built with Bevy and heightmaps"

[dependencies]
bevy = { version = "0.16", features = ["jpeg", "png"] }
bevy_heightmap = "0.4.1"
futures-lite = "2.6.0"
image = "0.24"
wgpu = "26.0.1"
serde = { version = "1", features = ["derive"] }
ron = "0.8"
thiserror = "1"
rand = "0.9.2"
rand_chacha = "0.9.0"
